export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';

export const GET_MY_BOOKS_REQUEST = 'GET_MY_BOOKS_REQUEST';
export const GET_MY_BOOKS_SUCCESS = 'GET_MY_BOOKS_SUCCESS';
export const GET_MY_BOOKS_FAILURE = 'GET_MY_BOOKS_FAILURE';

export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';

export const REQUEST_TRADE_REQUEST = 'REQUEST_TRADE_REQUEST';
export const REQUEST_TRADE_SUCCESS = 'REQUEST_TRADE_SUCCESS';
export const REQUEST_TRADE_FAILURE = 'REQUEST_TRADE_FAILURE';

export const APPROVE_TRADE_REQUEST = 'APPROVE_TRADE_REQUEST';
export const APPROVE_TRADE_SUCCESS = 'APPROVE_TRADE_SUCCESS';
export const APPROVE_TRADE_FAILURE = 'APPROVE_TRADE_FAILURE';

export const DENY_TRADE_REQUEST = 'DENY_TRADE_REQUEST';
export const DENY_TRADE_SUCCESS = 'DENY_TRADE_SUCCESS';
export const DENY_TRADE_FAILURE = 'DENY_TRADE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
