const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST';
const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';

const GET_MY_BOOKS_REQUEST = 'GET_MY_BOOKS_REQUEST';
const GET_MY_BOOKS_SUCCESS = 'GET_MY_BOOKS_SUCCESS';
const GET_MY_BOOKS_FAILURE = 'GET_MY_BOOKS_FAILURE';

const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';

const REQUEST_TRADE_REQUEST = 'REQUEST_TRADE_REQUEST';
const REQUEST_TRADE_SUCCESS = 'REQUEST_TRADE_SUCCESS';
const REQUEST_TRADE_FAILURE = 'REQUEST_TRADE_FAILURE';

const APPROVE_TRADE_REQUEST = 'APPROVE_TRADE_REQUEST';
const APPROVE_TRADE_SUCCESS = 'APPROVE_TRADE_SUCCESS';
const APPROVE_TRADE_FAILURE = 'APPROVE_TRADE_FAILURE';

const DENY_TRADE_REQUEST = 'DENY_TRADE_REQUEST';
const DENY_TRADE_SUCCESS = 'DENY_TRADE_SUCCESS';
const DENY_TRADE_FAILURE = 'DENY_TRADE_FAILURE';

const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
